;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0x0000FF       ;cut window by this color (default red)
			;not used with PNG in Win2k/XP


DisableDate=0
DateColor=0x000000	; gray - 0x787878
DateFont=Arial Narrow
DateFontSize=7
DateCenterX=99
DateCenterY=157

HourColor=0xffffff      ;color of hour hand - 0xAA9696
HourLength=35           ;length of hour hand
HourLap=2               ;overlap of hour hand
HourWidth=3             ;width of hour hand

MinuteColor=0xc0c0c0    ;color of minute hand - 0xAA9696
MinuteLength=45         ;length of minute hand
MinuteLap=5             ;overlap of minute hand
MinuteWidth=2           ;width of minute hand

SecondColor=0x553FFF    ;color of second hand
SecondLength=47         ;length of second hand
SecondLap=15            ;overlap of second hand
SecondWidth=1           ;width of second hand


