;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0xFFF2FF       ;cut window by this color (default red)
DisableAMPM=0           ;show AM/PM indicator (default 0)
AMPMColor=0x201010	;color of AM/PM indicator

HourColor=0x501A1A      ;color of hour hand
HourLength=33           ;length of hour hand
HourLap=0               ;overlap of hour hand
HourWidth=3             ;width of hour hand

MinuteColor=0x501A1A    ;color of minute hand
MinuteLength=51         ;length of minute hand
MinuteLap=0             ;overlap of minute hand
MinuteWidth=2           ;width of minute hand

SecondColor=0x553FFF    ;color of second hand
SecondLength=54         ;length of second hand
SecondLap=0             ;overlap of second hand
SecondWidth=1           ;width of second hand

;CenterX=60             ;center point's X (default image_width / 2)
;CenterY=60             ;center point's Y (default image_height / 2)
