;Cappuccino ClocX skin by Shak @ AquaXP.com
;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0x0000FF       ;cut window by this color (default red)
DisableAMPM=1           ;show AM/PM indicator (default 0)
AMPMColor=0x787878	;color of AM/PM indicator

HourColor=0x808080      ;color of hour hand
HourLength=30           ;length of hour hand
HourLap=0               ;overlap of hour hand
HourWidth=2             ;width of hour hand

MinuteColor=0x404040    ;color of minute hand
MinuteLength=50         ;length of minute hand
MinuteLap=0             ;overlap of minute hand
MinuteWidth=2           ;width of minute hand

SecondColor=0x909090    ;color of second hand
SecondLength=50         ;length of second hand
SecondLap=10            ;overlap of second hand
SecondWidth=1           ;width of second hand

;CenterX=68             ;center point's X (default image_width / 2)
;CenterY=66             ;center point's Y (default image_height / 2)
