;Klok Dark — charcoal face with cream hands
[Settings]
CenterX=100
CenterY=100
HourColor=0xCDE1EB
HourLength=55
HourLap=10
HourWidth=4
MinuteColor=0xBED2DC
MinuteLength=76
MinuteLap=10
MinuteWidth=2.5
SecondColor=0x2864CD
SecondLength=87
SecondLap=14
SecondWidth=1.5
DisableAMPM=0
AMPMColor=0x87949B
AMPMFont=
AMPMFontSize=12
AMPMCenterX=100
AMPMCenterY=140
DisableDate=0
DateColor=0x87949B
DateFont=
DateFontSize=12
DateCenterX=100
DateCenterY=60