;Klok Classic — clean white face
[Settings]
CenterX=100
CenterY=100
HourColor=0x2D2D2D
HourLength=55
HourLap=10
HourWidth=4
MinuteColor=0x2D2D2D
MinuteLength=76
MinuteLap=10
MinuteWidth=2.5
SecondColor=0x232DD2
SecondLength=87
SecondLap=14
SecondWidth=1.5
DisableAMPM=0
AMPMColor=0x6E6E6E
AMPMFont=
AMPMFontSize=12
AMPMCenterX=100
AMPMCenterY=140
DisableDate=0
DateColor=0x6E6E6E
DateFont=
DateFontSize=12
DateCenterX=100
DateCenterY=60