;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0x00ff00       ;cut window by this color (default red)
DisableAMPM=0           ;show AM/PM indicator (default 0)
AMPMColor=0x201010	;color of AM/PM indicator

HourPNG=MClkhrHand.hpng
HourPNGCenterDist=33

MinutePNG=MClkminHand.hpng
MinutePNGCenterDist=43



SecondColor=0x555555    ;color of second hand
SecondLength=100        ;length of second hand
SecondLap=0             ;overlap of second hand
SecondWidth=2           ;width of second hand


CenterX=122            ;center point's X (default image_width / 2)
CenterY=123            ;center point's Y (default image_height / 2)
