;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0x0000FF       ;cut window by this color (default red)
ShowAMPM=1              ;show AM/PM indicator (default 0)
AMPMColor=0x00000000	;color of AM/PM indicator

HourColor=0xFFFFFF    ;color of hour hand
HourLength=30           ;length of hour hand
HourLap=0               ;overlap of hour hand
HourWidth=3             ;width of hour hand

MinuteColor=0xFFFFFF  ;color of minute hand
MinuteLength=48         ;length of minute hand
MinuteLap=0             ;overlap of minute hand
MinuteWidth=2           ;width of minute hand

SecondColor=0xFFFFFF  ;color of second hand
SecondLength=50         ;length of second hand
SecondLap=0             ;overlap of second hand
SecondWidth=1           ;width of second hand

CenterX=85             ;center point's X (default image_width / 2)
CenterY=95             ;center point's Y (default image_height / 2)

