;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0xff0000       ;cut window by this color (default red)
DisableAMPM=0           ;show AM/PM indicator (default 0)
AMPMColor=0x201010	;color of AM/PM indicator

HourPNG=romanold/romanoldhour.png
HourPNGCenterDist=44

MinutePNG=romanold/romanoldmin.png
MinutePNGCenterDist=44



SecondColor=0x758799   ;color of second hand
SecondLength=0          ;length of second hand
SecondLap=0            ;overlap of second hand
SecondWidth=0           ;width of second hand

CenterX=186              ;center point's X (default image_width / 2)
CenterY=163             ;center point's Y (default image_height / 2)
