; Made by ´Â¤ñ©`ÇfÆõÇr@bbs.sos-dan.hk

[Settings]
CutColor=0xFFFFFF
DisableAMPM=1
AMPMColor=0x787878
AMPMFont=Times New Roman
AMPMFontSize=10
AMPMCenterX=61
AMPMCenterY=88
DisableDate=1
DateColor=0x787878
DateFont=Arial
DateFontSize=12
DateCenterX=62
DateCenterY=45

HourColor=0x00FF00
HourLength=50
HourLap=1
HourWidth=5
MinuteColor=0x00FFFF
MinuteLength=60
MinuteLap=2
MinuteWidth=3
SecondColor=0x0000FF
SecondLength=70
SecondLap=3
SecondWidth=1

CenterX=75
CenterY=80