; Made by ´Â¤ñ©`ÇfÆõÇr@bbs.sos-dan.hk

[Settings]
CutColor=0xFFFFFF
DisableAMPM=0
AMPMColor=0x000000
AMPMFont=MS PGothic
AMPMFontSize=18
AMPMCenterX=80
AMPMCenterY=145
DisableDate=1
DateColor=0x000000
DateFont=MS PGothic
DateFontSize=18
DateCenterX=75
DateCenterY=35

HourColor=0x00FF00
HourLength=50
HourLap=1
HourWidth=5
MinuteColor=0x00FFFF
MinuteLength=60
MinuteLap=2
MinuteWidth=3
SecondColor=0x0000FF
SecondLength=70
SecondLap=3
SecondWidth=1

CenterX=75
CenterY=80