;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0xC5BE47       ;0000FF       ;cut window by this color (default red)
ShowAMPM=0              ;show AM/PM indicator (default 0)
AMPMColor=0xAA5F55      ;color of AM/PM indicator

HourColor=0x333333      ;color of hour hand
HourLength=22           ;length of hour hand
HourLap=2               ;overlap of hour hand
HourWidth=2             ;width of hour hand

MinuteColor=0x333333    ;color of minute hand
MinuteLength=33         ;length of minute hand
MinuteLap=2             ;overlap of minute hand
MinuteWidth=2           ;width of minute hand

SecondColor=0x553FFF    ;color of second hand
SecondLength=40         ;length of second hand
SecondLap=0             ;overlap of second hand
SecondWidth=1           ;width of second hand

CenterX=42              ;center point's X (default image_width / 2)
CenterY=42              ;center point's Y (default image_height / 2)

;load hour hand image from PNG file
;HourPNG=TOM 06-hr.png
;HourPNGCenterDist=0   ;distance from center of PNG image to point that should be in center of clock
;load minute hand image from PNG file:
;MinutePNG=TOM 06-min.png
;MinutePNGCenterDist=8
;load second hand image from PNG file:
;SecondPNG=TOM 06-sec.png
;SecondPNGCenterDist=15