;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0x0000FF       ;cut window by this color (default red)
DisableAMPM=0           ;show AM/PM indicator (default 0)
AMPMColor=0x787878	;color of AM/PM indicator

HourColor=0x00000000    ;color of hour hand
HourLength=28           ;length of hour hand
HourLap=5               ;overlap of hour hand
HourWidth=4             ;width of hour hand

MinuteColor=0x00000000  ;color of minute hand
MinuteLength=46         ;length of minute hand
MinuteLap=5             ;overlap of minute hand
MinuteWidth=3           ;width of minute hand

SecondColor=0x00000000  ;color of second hand
SecondLength=47         ;length of second hand
SecondLap=0             ;overlap of second hand
SecondWidth=1           ;width of second hand

;CenterX=60             ;center point's X (default image_width / 2)
;CenterY=60             ;center point's Y (default image_height / 2)
