;all colors are in BGR format (hexadecimal or number)
[Settings]
CutColor=0xC5BE47	;0000FF       ;cut window by this color (default red)
ShowAMPM=1              ;show AM/PM indicator (default 0)
AMPMColor=0xAA5F55	;color of AM/PM indicator

HourColor=0xC5BE47	;AA5F55      ;color of hour hand
HourLenght=33           ;length of hour hand
HourLap=5               ;overlap of hour hand
HourWidth=3             ;width of hour hand

MinuteColor=0xC5BE47	;AA5F55    ;color of minute hand
MinuteLenght=47         ;length of minute hand
MinuteLap=5             ;overlap of minute hand
MinuteWidth=2           ;width of minute hand

SecondColor=0xC5BE47	;E8F08E    ;color of second hand
SecondLenght=54         ;length of second hand
SecondLap=10             ;overlap of second hand
SecondWidth=1           ;width of second hand

CenterX=80              ;center point's X (default image_width / 2)
CenterY=52              ;center point's Y (default image_height / 2)
